/*
 * Copyright (c) 2023 Chris K Wensel <chris@wensel.net>. All Rights Reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package clusterless;

import clusterless.substrate.SubstrateProviders;
import picocli.CommandLine;

import java.util.concurrent.Callable;

@CommandLine.Command(name = "cls", mixinStandardHelpOptions = true)
public class Main implements Callable<Integer> {

    private final SubstrateProviders providers;

    public static void main(String[] args) {

        SubstrateProviders providers = new SubstrateProviders();

        CommandLine commandLine = new CommandLine(new Main(providers));
        providers.substrates().forEach(commandLine::addSubcommand);

        commandLine.execute(args);
    }

    public Main(SubstrateProviders providers) {
        this.providers = providers;
    }

    @Override
    public Integer call() throws Exception {
        return 0;
    }

    @CommandLine.Command()
    public Integer substrates() {
        providers.names().forEach(System.out::println);
        return 0;
    }
}
