/*
 * Copyright (c) 2023-2025 Chris K Wensel <chris@wensel.net>. All Rights Reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

package clusterless.cls;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * version.properties is generated by the writeVersionProperties task and must always reach the
 * main resources; Versions.clsVersion() falls back to the wip value when it is absent, which
 * would otherwise hide a dropped resource at runtime.
 */
class VersionPropertiesTest {
    @Test
    void versionPropertiesOnClasspath() throws IOException {
        try (InputStream inputStream = getClass().getClassLoader().getResourceAsStream("version.properties")) {
            assertNotNull(inputStream, "version.properties is missing from the main resources");

            Properties properties = new Properties();
            properties.load(inputStream);

            String release = properties.getProperty("clusterless.release.full");

            assertNotNull(release, "clusterless.release.full is missing");
            assertFalse(release.isBlank(), "clusterless.release.full is blank");
        }
    }
}
