= Command Line Usage

Proposed commands for the cli.

The command line:

====
cls [command] [<files>]
====

== Commands

global commands:

* `bootstrap` - initializes the cloud env for a given substrate, account, and region
* `show`  - show the available model types and print schemas
** `providers`  - show the available substrates
** `models`  - show the available model types and print schemas

project scope commands:

* `substrates` - list all deployed substrates
* `regions` - list all deployed regions
* `projects` - list all deployed projects
* `arcs` - list all deployed arcs
* `boundarys` - list all deployed boundaries
* `verify` - confirm the project files will render
* `deploy` - renders then deploys the declared project configurations
* `diff` - renders then compares the local project configuration with deployed configuration
* `enable` - enable the listeners on the project, arc, or boundary
* `disable` - disable the listeners on the project, arc, or boundary
* `destroy` - destroys the project
* `status` - status of lot executions (for a time range) within a project, arc, or boundary
* `exec` - execute project arc(s) against give lots for testing, replay, or backfill
* `gaps` - show missing lots in a project, or given arc, and any missing upstream source arcs
* `rollback` - mark all completed lots for a given arc as replaceable so that any exec will overwrite them
* `dupes` - show or remove duplicate objects
* `local` - execute process locally

== Files

The `cls` client will process all given 'project' files.

Each file is a single or array of deployments, where a deployment has a single placement and declaration.

A placement is the substrate, account id, region, and stage, where a deployment declaration will be deployed.

The declaration consists of the construct that will be managed as a single versioned project unit.

That is, if a project as a declaration for each of two regions (in AWS), us-west-1 and us-west-2, there will need to be two files, one for each region.

If identical deployments are expected, except for the region, each file should be identical, except where a declared resource could collide with a resource in another region (like an S3 bucket).

It is required all the deployment files have the same project name and version in a given deploy.

See link:adr/0002-static-json-as-configuration.md[Static JSON as configuration].

