name: Clusterless Build
run-name: "Push: from ${{ github.actor }}"
on: [ push ]
jobs:
  run-all-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Install Node
        uses: actions/setup-node@v3

      - name: Install CDK
        run: npm install -g aws-cdk@2.72.1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup Env
        run: echo "${{ vars.GRADLE_PROPERTIES }}" > gradle.properties

      - name: Run Tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
        run: |
          ./gradlew --no-daemon --info --stacktrace check scenarios
