name: Clusterless Scenario Tests
run-name: "Push: from ${{ github.actor }}"
on:
  push:
    branches:
      - '*-scenarios'
    paths-ignore:
      - '*.txt'
      - '*.md'
      - '*.adoc'
jobs:
  run-all-scenarios:
    concurrency: scenarios-us-east-2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Install Node
        uses: actions/setup-node@v3

      - name: Install CDK
        run: npm install -g aws-cdk@2.80.0

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup Env
        run: echo "${{ vars.GRADLE_PROPERTIES_EAST }}" > gradle.properties

      - name: Run Scenarios
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
        run: |
          ./gradlew --no-daemon --info --stacktrace scenarios

      - name: Archive Scenario Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: scenario-results
          path: |
            clusterless-scenario/build/scenarios/*
            !clusterless-scenario/build/scenarios/**/cdk.out
          retention-days: 5
