name: Clusterless Wip Build
run-name: "Push: from ${{ github.actor }}"
on:
  push:
    branches:
      - 'wip-*'
      - '!*-scenarios'
    paths-ignore:
      - '*.txt'
      - '*.md'
      - '*.adoc'
jobs:
  run-all-tests-and-release:
    concurrency: scenarios-us-west-2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Install Node
        uses: actions/setup-node@v3

      - name: Install CDK
        run: npm install -g aws-cdk@2.87.0

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup Env
        run: echo "${{ vars.GRADLE_PROPERTIES }}" > gradle.properties

      - name: Run Tests
        run: |
          ./gradlew --no-daemon --info --stacktrace check

      - name: Run Scenarios
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
        run: |
          ./gradlew --no-daemon --info --stacktrace scenarios

      - name: Archive Scenario Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: scenario-results
          path: |
            clusterless-scenario/build/scenarios/*
            !clusterless-scenario/build/scenarios/**/cdk.out
          retention-days: 5

      - name: Release
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
        run: |
          ./gradlew --no-daemon --info --stacktrace release
